App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name="signup" ),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.user_profile, name="profile")
]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>', views.add_to_cart, name="add"),
    path('cart/', views.cart_view, name="cart"),
    path('remove/<pk>/', views.remove_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = "App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders")
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = "App_Shop"

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail' )
]

My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title_block %}E-com | Jakir {% endblock %}</title>
  <style>
  a{
    text-decoration: none;
  }
  .card{
    height:350px;
  }
  .card-product:after {
    content: "";
    display: table;
    clear:both;
    visibility:hidden;
  }
  .card-product .pricenew, .card-product .price {
    margin-right:5px;
  }
  .card-product .price.old {
    color:#999;
  }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow:hidden;
    height:220px;
    text-align:center;
  }
  .card-product .img-wrap img{
    max-height:100%;
    max-width:100%;
    object-fit: cover;
  }
  .card-product .info-wrap{
    overflow: hidden;
    padding:15px;
    border-top: 1px solid #eee;
  }
  .card-product .action-wrap{
    padding-top: 4px;
    pmargin-top: 4px;
  }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee;
  }
  .card-product .title {
    margin-top: 0px;
  }
  </style>
</head>
<body>
      {% include 'navbar.html' %}
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
      {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %} alert-dismissible fade show"  role="alert">
           {{ message }}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
      {% endif %}
    </div>
    {% block body_block %}

    {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Django E-commerce</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
         <ul class="navbar-nav ">
          {% if request.user.is_authenticated %}
          <li class="nav-item"> <a href="{% url 'App_Order:cart' %}" class="nav-link"><i class="fa fa-shopping-cart"></i> Cart<span class="badge bg-light text-dark">{{ request.user | cart_total }}</span></a></li>
          <li class="nav-item dropdown">
            <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> </a> -->
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user-tie"> {{request.user.profile.username}}</i></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
  </div>
</nav>